services:
  - type: web
    name: legacy-xmd-bot
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: SESSION_ID
        sync: false
      - key: OWNER_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: TZ
        value: UTC
    # Resource allocation for better performance
    region: oregon
    # Health check configuration
    healthCheckPath: /health